# Generated by Django 2.2.7 on 2020-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
